#include <Geode/modify/SetupAreaMoveTriggerPopup.hpp>
#include <Geode/modify/SetupAreaTriggerPopup.hpp>
#include "../shared/Settings.hpp"

using namespace geode::prelude;

#define IS_THERE_A_WORD_IN_MY_MOTHER_TONGUE_HAVE_I_PASSED_IT_BY_HEARD_IT_WHEN_I_WAS_YOUNG_CAUSE_I_JUST_CANT_EXPLAIN_THE_WAY_I_FEEL_FOR_ONCE_AND_I_DONT_KNOW_AND_I_DONT_KNOW_AND_I_DONT_KNOW_I_CAN_ALWAYS_FIND_THE_PHRASE_BUT_WHEN_I_LOOK_INTO_YOUR_FUCK_FUCK_I_JUST_DONT_KNOW_WHAT_TO_SAY_FUCK_FUCK_IM_JUST_HAPPY_THAT_YOURE_HERE_IT_WOULD_KILL_ME_IF_YOU_LEFT_IF_YOU_DIDNT_WANT_TO_STAY_WHO_AM_I_TO_INTERJECT_RATHER_LIVE_THAN_DIE_FOR_YOU_THERES_NO_CERTAINTY_IN_DEATH_CERTAINLY_I_FOUND_YOU_NOW_AND_ID_FIND_YOU_IN_THE_NEXT_AND_ID_FIND_YOU_IN_THE_SWELTERING_HEAT_AND_THE_CAROLINA_SUMMER_YOU_LEARN_TO_FIND_PEACE_IN_THE_PIECES_OF_EACH_OTHER_AND_THERES_AND_THERES_A_BEAUTY_IN_THE_FACT_THAT_IF_YOU_FEEL_IT_ONCE_YOU_CAN_NEVER_TAKE_IT_BACK_YOURE_EVERYTHING_I_LACK_NO_YOURE_EVERYTHING_I_HAVE_I_COULD_TRY_EXPLAINING_THAT_BUT_I_DONT_KNOW_I_CAN_ALWAYS_FIND_THE_PHRASE_BUT_WHEN_I_LOOK_INTO_YOUR_FUCK_FUCK_I_JUST_DONT_KNOW_WHAT_TO_SAY_FUCK_FUCK_IM_JUST_HAPPY_THAT_YOURE_HERE_IT_WOULD_KILL_ME_IF_YOU_LEFT_IF_YOU_DIDNT_WANT_TO_STAY_WHO_AM_I_TO_INTERJECT_RATHER_LIVE_THAN_DIE_FOR_YOU_THERES_NO_CERTAINTY_IN_DEATH_CERTAINLY_I_FOUND_YOU_NOW_AND_ID_FIND_YOU_IN_THE_NEXT_AND_ID_FIND_YOU_IN_THE_FUCK_I_CAN_ALWAYS_FIND_THE_PHRASE_BUT_WHEN_I_LOOK_INTO_YOUR_FUCK_FUCK_I_JUST_DONT_KNOW_WHAT_TO_SAY_FUCK_FUCK_FUCK_FUCK_FUCK(hook, className) \
    class $modify( hook, className ) { \
        struct Fields { \
            std::vector<EffectGameObject*> triggers; \
        }; \
    \
        bool init(EnterEffectObject* p0, CCArray* p1) { \
            if (! className ::init(p0, p1)) return false; \
            if (!Settings::AreaPreviews::enabled) return true; \
    \
            auto fields = m_fields.self(); \
            if (p0) fields->triggers.push_back(p0); \
            else for (auto obj : CCArrayExt<EffectGameObject*>(p1)) fields->triggers.push_back(obj); \
    \
            auto toggler = CCMenuItemToggler::create( \
                CCSprite::createWithSpriteFrameName("GJ_checkOff_001.png"), \
                CCSprite::createWithSpriteFrameName("GJ_checkOn_001.png"), \
                this, menu_selector( hook ::onAreaPreviewToggler) \
            ); \
            toggler->setID("enable-preview-toggle"_spr); \
            toggler->setPosition(-100.0f, 240.0f); \
            toggler->setScale(0.5f); \
            bool toggle = true; \
            for (auto obj : fields->triggers) { \
                if (!obj->m_isIceBlock) { toggle = false; break; } \
            } \
            toggler->toggle(toggle); \
            addObjectToPage(toggler, 0); \
            m_buttonMenu->addChild(toggler); \
    \
            auto label = CCLabelBMFont::create("Enable\nPreview", "bigFont.fnt"); \
            label->setID("enable-preview-label"_spr); \
            label->setPosition(ccp(-112.5f, 240.0f) + m_buttonMenu->getPosition()); \
            label->setScale(0.225f); \
            label->setAnchorPoint({1.0f, 0.5f}); \
            addObjectToPage(label, 0); \
            m_mainLayer->addChild(label); \
    \
            return true; \
        } \
    \
        void onAreaPreviewToggler(CCObject* sender) { \
            bool toggle = !static_cast<CCMenuItemToggler*>(sender)->m_toggled; \
            for (auto obj : m_fields->triggers) { \
                obj->m_isIceBlock = toggle; \
            } \
        } \
    }
    
IS_THERE_A_WORD_IN_MY_MOTHER_TONGUE_HAVE_I_PASSED_IT_BY_HEARD_IT_WHEN_I_WAS_YOUNG_CAUSE_I_JUST_CANT_EXPLAIN_THE_WAY_I_FEEL_FOR_ONCE_AND_I_DONT_KNOW_AND_I_DONT_KNOW_AND_I_DONT_KNOW_I_CAN_ALWAYS_FIND_THE_PHRASE_BUT_WHEN_I_LOOK_INTO_YOUR_FUCK_FUCK_I_JUST_DONT_KNOW_WHAT_TO_SAY_FUCK_FUCK_IM_JUST_HAPPY_THAT_YOURE_HERE_IT_WOULD_KILL_ME_IF_YOU_LEFT_IF_YOU_DIDNT_WANT_TO_STAY_WHO_AM_I_TO_INTERJECT_RATHER_LIVE_THAN_DIE_FOR_YOU_THERES_NO_CERTAINTY_IN_DEATH_CERTAINLY_I_FOUND_YOU_NOW_AND_ID_FIND_YOU_IN_THE_NEXT_AND_ID_FIND_YOU_IN_THE_SWELTERING_HEAT_AND_THE_CAROLINA_SUMMER_YOU_LEARN_TO_FIND_PEACE_IN_THE_PIECES_OF_EACH_OTHER_AND_THERES_AND_THERES_A_BEAUTY_IN_THE_FACT_THAT_IF_YOU_FEEL_IT_ONCE_YOU_CAN_NEVER_TAKE_IT_BACK_YOURE_EVERYTHING_I_LACK_NO_YOURE_EVERYTHING_I_HAVE_I_COULD_TRY_EXPLAINING_THAT_BUT_I_DONT_KNOW_I_CAN_ALWAYS_FIND_THE_PHRASE_BUT_WHEN_I_LOOK_INTO_YOUR_FUCK_FUCK_I_JUST_DONT_KNOW_WHAT_TO_SAY_FUCK_FUCK_IM_JUST_HAPPY_THAT_YOURE_HERE_IT_WOULD_KILL_ME_IF_YOU_LEFT_IF_YOU_DIDNT_WANT_TO_STAY_WHO_AM_I_TO_INTERJECT_RATHER_LIVE_THAN_DIE_FOR_YOU_THERES_NO_CERTAINTY_IN_DEATH_CERTAINLY_I_FOUND_YOU_NOW_AND_ID_FIND_YOU_IN_THE_NEXT_AND_ID_FIND_YOU_IN_THE_FUCK_I_CAN_ALWAYS_FIND_THE_PHRASE_BUT_WHEN_I_LOOK_INTO_YOUR_FUCK_FUCK_I_JUST_DONT_KNOW_WHAT_TO_SAY_FUCK_FUCK_FUCK_FUCK_FUCK(SetupAreaMoveTriggerPopupHook, SetupAreaMoveTriggerPopup);
IS_THERE_A_WORD_IN_MY_MOTHER_TONGUE_HAVE_I_PASSED_IT_BY_HEARD_IT_WHEN_I_WAS_YOUNG_CAUSE_I_JUST_CANT_EXPLAIN_THE_WAY_I_FEEL_FOR_ONCE_AND_I_DONT_KNOW_AND_I_DONT_KNOW_AND_I_DONT_KNOW_I_CAN_ALWAYS_FIND_THE_PHRASE_BUT_WHEN_I_LOOK_INTO_YOUR_FUCK_FUCK_I_JUST_DONT_KNOW_WHAT_TO_SAY_FUCK_FUCK_IM_JUST_HAPPY_THAT_YOURE_HERE_IT_WOULD_KILL_ME_IF_YOU_LEFT_IF_YOU_DIDNT_WANT_TO_STAY_WHO_AM_I_TO_INTERJECT_RATHER_LIVE_THAN_DIE_FOR_YOU_THERES_NO_CERTAINTY_IN_DEATH_CERTAINLY_I_FOUND_YOU_NOW_AND_ID_FIND_YOU_IN_THE_NEXT_AND_ID_FIND_YOU_IN_THE_SWELTERING_HEAT_AND_THE_CAROLINA_SUMMER_YOU_LEARN_TO_FIND_PEACE_IN_THE_PIECES_OF_EACH_OTHER_AND_THERES_AND_THERES_A_BEAUTY_IN_THE_FACT_THAT_IF_YOU_FEEL_IT_ONCE_YOU_CAN_NEVER_TAKE_IT_BACK_YOURE_EVERYTHING_I_LACK_NO_YOURE_EVERYTHING_I_HAVE_I_COULD_TRY_EXPLAINING_THAT_BUT_I_DONT_KNOW_I_CAN_ALWAYS_FIND_THE_PHRASE_BUT_WHEN_I_LOOK_INTO_YOUR_FUCK_FUCK_I_JUST_DONT_KNOW_WHAT_TO_SAY_FUCK_FUCK_IM_JUST_HAPPY_THAT_YOURE_HERE_IT_WOULD_KILL_ME_IF_YOU_LEFT_IF_YOU_DIDNT_WANT_TO_STAY_WHO_AM_I_TO_INTERJECT_RATHER_LIVE_THAN_DIE_FOR_YOU_THERES_NO_CERTAINTY_IN_DEATH_CERTAINLY_I_FOUND_YOU_NOW_AND_ID_FIND_YOU_IN_THE_NEXT_AND_ID_FIND_YOU_IN_THE_FUCK_I_CAN_ALWAYS_FIND_THE_PHRASE_BUT_WHEN_I_LOOK_INTO_YOUR_FUCK_FUCK_I_JUST_DONT_KNOW_WHAT_TO_SAY_FUCK_FUCK_FUCK_FUCK_FUCK(SetupAreaTriggerPopupHook, SetupAreaTriggerPopup);